### ISSUE TITLE
failed tests on libgfapi(glusterfs-api) 11 

### ISSUE THREAD

**Issue by kmlebedev** [kmlebedev/gogfapi#2]
req
```
libgfapi0-11.1-1.el8s.x86_64
libgfapi-devel-11.1-1.el8s.x86_64
libgcc-8.5.0-22.el8.x86_64
gcc-8.5.0-22.el8.x86_64
```

```
go test  -v .
=== RUN   TestInit
--- PASS: TestInit (0.00s)
=== RUN   TestSetLogging
--- PASS: TestSetLogging (0.00s)
=== RUN   TestMount
    gfapi_test.go:45: Failed to mount volume. error: mount failed: no such file or directory
--- FAIL: TestMount (0.01s)
=== RUN   TestMkdirAll
    gfapi_test.go:54: MkdirAll "/tmp/_TestMkdirAll_/dir/./dir2": mkdir /tmp: input/output error
--- FAIL: TestMkdirAll (0.00s)
=== RUN   TestCreate
    gfapi_test.go:104: Failed to create file. Error = create test: input/output error
--- FAIL: TestCreate (0.00s)
=== RUN   TestClose1
--- FAIL: TestClose1 (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x52e08e]

goroutine 22 [running]:
testing.tRunner.func1.2({0x54aea0, 0x875da0})
	/usr/local/go/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1635 +0x35e
panic({0x54aea0?, 0x875da0?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/kmlebedev/gogfapi/gfapi.(*File).Close(0x884700?)
	/home/whitefox/gogfapi/sources-blExtdgG3C/gfapi/file.go:34 +0xe
github.com/kmlebedev/gogfapi/gfapi.TestClose1(0xc00018e820)
	/home/whitefox/gogfapi/sources-blExtdgG3C/gfapi/gfapi_test.go:110 +0x26
testing.tRunner(0xc00018e820, 0x57b4a8)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1743 +0x390
FAIL	github.com/kmlebedev/gogfapi/gfapi	0.029s
FAIL
```

**Comment by kmlebedev** [comment]
make test volume
